---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      no_log: "{{ congif_no_log | default(true) }}"
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - name: Run pre-provision pre_task files in a block.
      tags: ['pre', 'never']
      block:
        - name: Run configured pre-provision ansible pre_task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ pre_provision_tasks | default(omit) }}"

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      when: configure_homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - name: Install additional packages.
      import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    - name: Configure OS X.
      import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
    - name: Run post-provision task files in a block.
      tags: ['post', 'never']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
