---
###  @TODO: Idempotent way to set ACL - `chmod +a "group:everyone deny delete"`
- name: Set ACL on directory to prevent deletion.
  ansible.builtin.command: 'chmod +a "group:everyone deny delete" ~/{{ item }}'
  loop: "{{ home_dirs_code }}"
