---
- name: Ensure ssh-agent is running and add SSH key to the ssh-agent
  shell: |
    eval "$(ssh-agent)"
    ssh-add --apple-use-keychain ~/.ssh/id_ed25519
- name: Add public key to allowed_signers
