---
name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Install dependencies with uv
        run: uv sync --group dev --locked

      - name: Lint YAML
        run: uv run --no-sync yamllint .
      - name: Lint Ansible
        run: uv run --no-sync ansible-lint
