---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 4"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pipenv'

      # - name: Get pipenv
      #   run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      # - name: Install pipenv
      #   run: pipenv install --deploy --verbose

      # - name: Lint YAML
      #   run: yamllint .

      # - name: Run ansible-lint
      #   uses: ansible/ansible-lint@main

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - run: pipenv run yamllint .
      - run: pipenv run ansible-lint
